* recover data
https://recoverit.wondershare.com/
* Android
  | ~adb shell~        | enter shell android      |
  | ~adb devices~      | List of devices attached |
  |                    | LGF240K90980405	device  |
  | ~adb kill-server~  |                          |
  | ~adb start-server~ |                          |

sudo apt install ffmpeg
adb shell screenrecord --output-format=h264 - | ffplay -

favorite

I want to stream my screen to vlc or something like this because the display is broken, I can see nothing on it. I want to do it via adb with the command

adb shell screenrecord --output-format=h264 - | vlc --demux h264 -
** enable control touch in windows
   echo "persist.service.adb.enable=1" >>/system/build.prop
   echo "persist.service.debuggable=1" >>/system/build.prop
   echo "persist.sys.usb.config=mass_storage,adb" >>/system/build.prop"
   reboot﻿
* command migrate
list disk
select disk 0
list partition
select partition 1
assign letter=b
exit

taskkill /im explorer.exe /f
explorer.exe

Click the Start button, click All Programs, right-click the Startup folder, and then click Open.
Open the location that contains the item you want to create a shortcut to.
Right-click the item, and then click Create Shortcut. The new shortcut appears in the same location as the original item.
* Autostart
Drag the shortcut into the Startup folder.
autostart C:\Users\jail\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup
** enable disable 
msconfig

regedit
