#!/bin/sh
exec tail -n +3 $0

menuentry '4.9.9 Arch Linux' --class arch --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-core repo kernel-true' {
	load_video
	set gfxpayload=keep
	insmod gzio
	insmod part_msdos
	insmod ext2
	set root='hd0,msdos1'
	if [ x$feature_platform_search_hint = xy ]; then
	  search --no-floppy --fs-uuid --set=root --hint-bios=hd0,msdos1 --hint-efi=hd0,msdos1 --hint-baremetal=ahci0,msdos5  93f9f2dd-2d67-4435-adf2-89b24d22a1b6
	else
	  search --no-floppy --fs-uuid --set=root 
	fi
	echo	'Loading Linux core repo kernel ...'
	linux	/boot/vmlinuz-linux-4.9.9 root=UUID=93f9f2dd-2d67-4435-adf2-89b24d22a1b6 rw  quiet
	echo	'Loading initial ramdisk ...'
	initrd	/boot/initramfs-linux-4.9.9.img
}